### ISSUE TITLE
java.lang.NoSuchFieldError: BasicConstraints

### ISSUE THREAD

**Issue by carlogaratti** [pinaraf/ebics#2]
Hi, 

i have created a jar from this project, imported the sample project 
http://sourceforge.net/projects/ebics/files/ebics_samples.zip/download
but when i run UserCreator on a French Bank (with the parameters) i receive the following error:

host: EBIXQUAL
partnerId: MYPARTNERID
userId: MYUSERID
2015-10-15 11:23:04,060  INFO - Initialisation de la configuration
2015-10-15 11:23:04,060  INFO - Création du nouvel utilisateur MYUSERID
Exception in thread "main" java.lang.NoSuchFieldError: BasicConstraints
    at org.kopi.ebics.certificate.X509Generator.generate(X509Generator.java:165)
    at org.kopi.ebics.certificate.X509Generator.generateA005Certificate(X509Generator.java:79)
    at org.kopi.ebics.certificate.CertificateManager.createA005Certificate(CertificateManager.java:91)
    at org.kopi.ebics.certificate.CertificateManager.create(CertificateManager.java:62)
    at org.kopi.ebics.client.User.createUserCertificates(User.java:155)
    at org.kopi.ebics.client.User.<init>(User.java:87)
    at org.kopi.ebics.test.UserCreator.createUser(UserCreator.java:92)
    at org.kopi.ebics.test.UserCreator.main(UserCreator.java:200)

Any help?

Note that all work if i use this binary http://sourceforge.net/projects/ebics/files/ebics-1.0.2-binaries.jar/download

**Comment by schelabi** [comment]
Hi,
I have the same error by doing the same things !
@carlogaratti , can you please tel us how did you fix that ? 

Thanks
